[CmdletBinding()]
param(
    [string] $Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $Path) {
    $Path = Split-Path -Parent $PSScriptRoot
}

$resolvedRoot = [System.IO.Path]::GetFullPath($Path)
if (-not [System.IO.Directory]::Exists($resolvedRoot)) {
    throw "Scan path does not exist: $resolvedRoot"
}

$excludedDirectoryNames = @(
    '.git'
    '.codex'
    '.idea'
    '.vscode'
    'attachments'
    'coverage'
    'Gallery'
    'node_modules'
    'Output'
    'outputs'
    'Release'
    'TestResults'
    'work'
)

$textExtensions = @(
    '.css'
    '.html'
    '.js'
    '.json'
    '.md'
    '.mjs'
    '.ps1'
    '.psd1'
    '.psm1'
    '.svg'
    '.txt'
    '.yaml'
    '.yml'
)

$approvedPublicEmails = @(
    'mark@controlaltdeletetechbits.co.uk'
    'noreply@github.com'
)

$approvedIdentifiers = @(
    '00000003-0000-0000-c000-000000000000'
    'df021288-bdef-4463-88db-98f22de89214'
    'f0ce5f0e-34dc-4c59-9c12-3e35b581e955'
)

$prohibitedAttributionTerms = @(
    ('Co' + 'dex')
    ('Chat' + 'GPT')
    ('Open' + 'AI')
)

$findings = [System.Collections.Generic.List[object]]::new()

function Add-AtlasReleaseFinding {
    param(
        [Parameter(Mandatory)]
        [string] $Category,

        [Parameter(Mandatory)]
        [string] $RelativePath,

        [Parameter(Mandatory)]
        [int] $LineNumber
    )

    $findings.Add([pscustomobject] @{
        Category = $Category
        File = $RelativePath
        Line = $LineNumber
    })
}

function Test-AtlasExcludedPath {
    param(
        [Parameter(Mandatory)]
        [string] $RelativePath
    )

    $segments = $RelativePath -split '[\\/]'
    return [bool]($segments | Where-Object { $_ -in $excludedDirectoryNames })
}

$candidateFiles = @(
    Get-ChildItem -LiteralPath $resolvedRoot -Recurse -File -Force |
        Where-Object {
            $relativePath = [System.IO.Path]::GetRelativePath($resolvedRoot, $_.FullName)
            -not (Test-AtlasExcludedPath -RelativePath $relativePath) -and
            $relativePath -ne 'tools\Test-IdentityAtlasRelease.ps1' -and
            $relativePath -ne 'tools\Test-IdentityAtlasPublicRelease.ps1' -and
            $_.Extension.ToLowerInvariant() -in $textExtensions
        }
)

$guidPattern = [regex]'(?i)\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b'
$emailPattern = [regex]'(?i)\b[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}\b'
$secretAssignmentPattern = [regex]'(?i)\b(access_token|refresh_token|client_secret|client_assertion|api[_-]?key|password)\b\s*[:=]\s*["'']?[A-Za-z0-9_./+\-]{8,}'
$privateKeyPattern = [regex]'(?i)-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----'
$jwtPattern = [regex]'\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b'
$windowsUserPathPattern = [regex]'(?i)\b[A-Z]:\\Users\\[^\\/:*?"<>|\r\n]+\\'
$posixUserPathPattern = [regex]'(?-i)/(?:Users|home)/[A-Za-z0-9._-]+/'
$tenantDomainPattern = [regex]'(?i)\.onmicrosoft\.com\b'
$syntheticIdentifierPattern = [regex]'(?i)^(?:[0-9a]0000000|71000000|72000000)-0000-0000-0000-000000000[0-9]{3}$'
$attributionContextPattern = [regex]'(?i)\b(author|co-author|coauthor|contributor|attribution|created by|generated by)\b'

foreach ($file in $candidateFiles) {
    $relativePath = [System.IO.Path]::GetRelativePath($resolvedRoot, $file.FullName)
    $lines = [System.IO.File]::ReadAllLines($file.FullName)

    for ($lineIndex = 0; $lineIndex -lt $lines.Count; $lineIndex++) {
        $line = $lines[$lineIndex]
        $lineNumber = $lineIndex + 1

        foreach ($term in $prohibitedAttributionTerms) {
            if (
                $attributionContextPattern.IsMatch($line) -and
                $line.IndexOf($term, [System.StringComparison]::OrdinalIgnoreCase) -ge 0
            ) {
                Add-AtlasReleaseFinding -Category 'Prohibited attribution term' -RelativePath $relativePath -LineNumber $lineNumber
            }
        }

        if ($windowsUserPathPattern.IsMatch($line) -or $posixUserPathPattern.IsMatch($line)) {
            Add-AtlasReleaseFinding -Category 'Local user path' -RelativePath $relativePath -LineNumber $lineNumber
        }

        if ($tenantDomainPattern.IsMatch($line)) {
            Add-AtlasReleaseFinding -Category 'Tenant domain' -RelativePath $relativePath -LineNumber $lineNumber
        }

        if ($privateKeyPattern.IsMatch($line)) {
            Add-AtlasReleaseFinding -Category 'Private key material' -RelativePath $relativePath -LineNumber $lineNumber
        }

        if ($jwtPattern.IsMatch($line)) {
            Add-AtlasReleaseFinding -Category 'Token-shaped value' -RelativePath $relativePath -LineNumber $lineNumber
        }

        $isKnownRedactionFixture = (
            $relativePath -eq 'Tests\IdentityAtlas.Tests.ps1' -and
            $line.Contains('eyJhbGciOiJub25l.secret.signature') -and
            $line.Contains('access_token=topsecret&code=abc123')
        )
        if (-not $isKnownRedactionFixture -and $secretAssignmentPattern.IsMatch($line)) {
            Add-AtlasReleaseFinding -Category 'Credential-shaped assignment' -RelativePath $relativePath -LineNumber $lineNumber
        }

        foreach ($emailMatch in $emailPattern.Matches($line)) {
            $email = $emailMatch.Value.ToLowerInvariant()
            if ($email -notin $approvedPublicEmails -and -not $email.EndsWith('.example')) {
                Add-AtlasReleaseFinding -Category 'Unapproved email address' -RelativePath $relativePath -LineNumber $lineNumber
            }
        }

        foreach ($guidMatch in $guidPattern.Matches($line)) {
            $identifier = $guidMatch.Value.ToLowerInvariant()
            $isSyntheticTestIdentifier = (
                $relativePath.StartsWith('Tests\', [System.StringComparison]::OrdinalIgnoreCase) -and
                $syntheticIdentifierPattern.IsMatch($identifier)
            )
            if ($identifier -notin $approvedIdentifiers -and -not $isSyntheticTestIdentifier) {
                Add-AtlasReleaseFinding -Category 'Unapproved identifier' -RelativePath $relativePath -LineNumber $lineNumber
            }
        }
    }
}

if ($findings.Count -gt 0) {
    $findings |
        Sort-Object File, Line, Category |
        Format-Table Category, File, Line -AutoSize |
        Out-String |
        Write-Warning
    throw "$($findings.Count) release safety finding or findings must be reviewed."
}

[pscustomobject] @{
    ScanRoot = $resolvedRoot
    ScannedFiles = $candidateFiles.Count
    Findings = 0
    Status = 'Passed'
}
